version: "3"
services:
  app:
    build: .
    ports:
      - "9090:80"
      - "9091:443"
    environment:
      - "ASPNETCORE_URLS=https://+;http://+"
      - "ASPNETCORE_HTTPS_PORT=9091"
      - "ASPNETCORE_ENVIRONMENT=Development"
    depends_on: 
      - "pg"
    volumes:
      - "/home/admin/pae/certs:/app/certs"
    restart: unless-stopped
  pg:
    image: "postgres"
    environment:
      - "POSTGRES_PASSWORD=anylearn"
      - "POSTGRES_USER=anylearn"
      - "POSTGRES_DB=anylearn"
    restart: unless-stopped