version: "3"
services:
  app:
    build: .
    ports:
      - "9090:80"
      - "9091:443"
    environment:
      - "ASPNETCORE_ENVIRONMENT=Development"
    depends_on: 
      - "pg"
    restart: unless-stopped
  pg:
    image: "postgres"
    environment:
      - "POSTGRES_PASSWORD=anylearn"
      - "POSTGRES_USER=anylearn"
      - "POSTGRES_DB=anylearn"
    #volumes:
      #- ./pg/db_data:/var/lib/postgresql/data
    restart: unless-stopped